version: '3.9'

services:

  postgres:

    image: postgres:16-alpine

    environment:

      POSTGRES_DB: uxr

      POSTGRES_USER: uxr

      POSTGRES_PASSWORD: uxr

    ports: ["5432:5432"]

    volumes:

      - pgdata:/var/lib/postgresql/data



  minio:

    image: minio/minio:RELEASE.2024-06-13T22-53-53Z

    command: server /data --console-address ":9001"

    environment:

      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}

      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}

    ports:

      - "9000:9000"

      - "9001:9001"

    volumes:

      - minio_data:/data



  minio-setup:

    image: minio/mc:latest

    depends_on: [minio]

    entrypoint: >

      /bin/sh -c "

      mc alias set local http://minio:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY &&

      mc mb -p local/uxr-recordings || true &&

      mc anonymous set none local/uxr-recordings &&

      echo 'MinIO ready' &&

      sleep 1

      "

    environment:

      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}

      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}



  firebase-auth-emulator:

    image: evolutecx/firebase-emulator

    ports: ["9099:9099"]

    environment:

      PORT: 9099

      FB_PROJECT_ID: ${FIREBASE_PROJECT_ID}

    # Note: provide a firebase.json and auth export if needed



  api:

    build:

      context: ./

      dockerfile: Dockerfile

    env_file: [.env.development]

    depends_on: [postgres, minio, minio-setup, firebase-auth-emulator]

    ports: ["8000:8000"]

    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./:/app



volumes:

  pgdata: {}

  minio_data: {}
