[tools]
python = "3.12"
uv = "latest"

[env]
_.python.venv = { path = ".venv", create = true }
DATABASE_URL = "postgresql+psycopg://uxr:uxr@localhost:5432/uxr"
FIREBASE_EMULATOR_HOST = "localhost:9099"
MINIO_ENDPOINT = "http://localhost:9000"
MINIO_ACCESS_KEY = "minioadmin"
MINIO_SECRET_KEY = "minioadmin"
APP_ENV = "development"
GCS_BUCKET_NAME = "verity-artifacts-dev"
PIPECAT_URL = "http://localhost:8080"
VERITY_API_BASE = "http://localhost:8000/api"

[tasks."check:format"]
description = "Check code formatting"
run = "make check-format"

[tasks."check:lint"]
description = "Check linting"
run = "make check-lint"

[tasks."check:types"]
description = "Check types"
run = "make check-types"

[tasks."fix:format"]
description = "Fix formatting"
run = "make fix-format"

[tasks."fix:lint"]
description = "Fix linting issues"
run = "make fix-lint"

[tasks.test-ci]
description = "Run tests in CI mode"
run = "make test-ci"