[project]
name = "verity-infra"
version = "0.1.0"
description = "Infrastructure as Code for Verity UXR Platform"
requires-python = ">=3.12"
dependencies = [
    "pulumi>=3.0.0,<4.0.0",
    "pulumi-gcp>=8.0.0,<9.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"