"""Add audio_recordings table

Revision ID: 0d943958dede
Revises: a06b0f827cdf
Create Date: 2025-09-28 10:27:43.757688

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d943958dede"
down_revision: str | Sequence[str] | None = "a06b0f827cdf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audio_recordings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("interview_id", sa.Integer(), nullable=False),
        sa.Column("uri", sa.String(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("mime_type", sa.String(), nullable=True),
        sa.Column("sample_rate_hz", sa.Integer(), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interviews.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audio_recordings_id"), "audio_recordings", ["id"], unique=False)
    op.create_index(
        op.f("ix_audio_recordings_interview_id"), "audio_recordings", ["interview_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audio_recordings_interview_id"), table_name="audio_recordings")
    op.drop_index(op.f("ix_audio_recordings_id"), table_name="audio_recordings")
    op.drop_table("audio_recordings")
    # ### end Alembic commands ###
