"""Add interview_guides table

Revision ID: 51d3bd529d66
Revises: 13d3783fcbd0
Create Date: 2025-09-27 12:59:55.029917

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "51d3bd529d66"
down_revision: str | Sequence[str] | None = "13d3783fcbd0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interview_guides",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("content_md", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["studies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_interview_guides_id"), "interview_guides", ["id"], unique=False)
    op.create_index(
        op.f("ix_interview_guides_study_id"), "interview_guides", ["study_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_interview_guides_study_id"), table_name="interview_guides")
    op.drop_index(op.f("ix_interview_guides_id"), table_name="interview_guides")
    op.drop_table("interview_guides")
    # ### end Alembic commands ###
