"""add unique constraint to organization name

Revision ID: 6404421f3ab8
Revises: 040b5add8cf3
Create Date: 2025-10-03 22:55:08.295166

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6404421f3ab8"
down_revision: str | Sequence[str] | None = "040b5add8cf3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_organizations_name", "organizations", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_organizations_name", "organizations", type_="unique")
    # ### end Alembic commands ###
