"""Update interviews table for self-led workflow

Revision ID: a06b0f827cdf
Revises: c2ba6cce71ba
Create Date: 2025-09-28 08:27:26.628487

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a06b0f827cdf"
down_revision: str | Sequence[str] | None = "c2ba6cce71ba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("interviews", sa.Column("access_token", sa.String(), nullable=False))
    op.add_column(
        "interviews", sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("interviews", sa.Column("transcript_url", sa.String(), nullable=True))
    op.add_column("interviews", sa.Column("recording_url", sa.String(), nullable=True))
    op.alter_column(
        "interviews", "interviewee_firebase_uid", existing_type=sa.VARCHAR(), nullable=True
    )
    op.create_index(op.f("ix_interviews_access_token"), "interviews", ["access_token"], unique=True)
    op.drop_column("interviews", "location")
    op.drop_column("interviews", "updated_at")
    op.drop_column("interviews", "scheduled_at")
    op.drop_column("interviews", "duration_minutes")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interviews",
        sa.Column("duration_minutes", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "interviews",
        sa.Column(
            "scheduled_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "interviews",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "interviews", sa.Column("location", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f("ix_interviews_access_token"), table_name="interviews")
    op.alter_column(
        "interviews", "interviewee_firebase_uid", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("interviews", "recording_url")
    op.drop_column("interviews", "transcript_url")
    op.drop_column("interviews", "completed_at")
    op.drop_column("interviews", "access_token")
    # ### end Alembic commands ###
