"""add self-led interview fields to study interview and participant models

Revision ID: bbb78d9096e9
Revises: bc699b4012a3
Create Date: 2025-10-10 22:22:11.796113

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bbb78d9096e9"
down_revision: str | Sequence[str] | None = "bc699b4012a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verity_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("firebase_uid", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_sign_in", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_verity_users_email"), "verity_users", ["email"], unique=True)
    op.create_index(
        op.f("ix_verity_users_firebase_uid"), "verity_users", ["firebase_uid"], unique=True
    )
    op.create_index(op.f("ix_verity_users_id"), "verity_users", ["id"], unique=False)
    op.create_table(
        "participant_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("verity_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "platform_identities",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["verity_user_id"],
            ["verity_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_participant_profiles_id"), "participant_profiles", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_participant_profiles_verity_user_id"),
        "participant_profiles",
        ["verity_user_id"],
        unique=True,
    )
    op.add_column("interviews", sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "interviews", sa.Column("external_participant_id", sa.String(length=255), nullable=True)
    )
    op.add_column("interviews", sa.Column("platform_source", sa.String(length=50), nullable=True))
    op.add_column("interviews", sa.Column("verity_user_id", sa.Integer(), nullable=True))
    op.add_column("interviews", sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "interviews", sa.Column("pipecat_session_id", sa.String(length=255), nullable=True)
    )
    op.create_index(
        op.f("ix_interviews_external_participant_id"),
        "interviews",
        ["external_participant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interviews_verity_user_id"), "interviews", ["verity_user_id"], unique=False
    )
    op.create_foreign_key(None, "interviews", "verity_users", ["verity_user_id"], ["id"])
    op.add_column("studies", sa.Column("slug", sa.String(length=63), nullable=True))
    op.add_column(
        "studies",
        sa.Column(
            "participant_identity_flow",
            sa.String(length=20),
            server_default="anonymous",
            nullable=False,
        ),
    )

    # Generate slugs for existing studies (id-based slugs for simplicity)
    op.execute("UPDATE studies SET slug = 'study-' || id::text WHERE slug IS NULL")

    # Now make slug NOT NULL and add unique constraint
    op.alter_column("studies", "slug", nullable=False)
    op.create_index(op.f("ix_studies_slug"), "studies", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_studies_slug"), table_name="studies")
    op.drop_column("studies", "participant_identity_flow")
    op.drop_column("studies", "slug")
    op.drop_constraint("interviews_verity_user_id_fkey", "interviews", type_="foreignkey")
    op.drop_index(op.f("ix_interviews_verity_user_id"), table_name="interviews")
    op.drop_index(op.f("ix_interviews_external_participant_id"), table_name="interviews")
    op.drop_column("interviews", "pipecat_session_id")
    op.drop_column("interviews", "claimed_at")
    op.drop_column("interviews", "verity_user_id")
    op.drop_column("interviews", "platform_source")
    op.drop_column("interviews", "external_participant_id")
    op.drop_column("interviews", "expires_at")
    op.drop_index(op.f("ix_participant_profiles_verity_user_id"), table_name="participant_profiles")
    op.drop_index(op.f("ix_participant_profiles_id"), table_name="participant_profiles")
    op.drop_table("participant_profiles")
    op.drop_index(op.f("ix_verity_users_id"), table_name="verity_users")
    op.drop_index(op.f("ix_verity_users_firebase_uid"), table_name="verity_users")
    op.drop_index(op.f("ix_verity_users_email"), table_name="verity_users")
    op.drop_table("verity_users")
    # ### end Alembic commands ###
