"""add display_name, description, and soft delete to organizations

Revision ID: bc699b4012a3
Revises: 6404421f3ab8
Create Date: 2025-10-04 18:02:05.306730

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bc699b4012a3"
down_revision: str | Sequence[str] | None = "6404421f3ab8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns (display_name nullable first for data migration)
    op.add_column("organizations", sa.Column("display_name", sa.String(), nullable=True))
    op.add_column("organizations", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "organizations", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )

    # Migrate existing data: copy name to display_name
    op.execute("UPDATE organizations SET display_name = name WHERE display_name IS NULL")

    # Now make display_name NOT NULL
    op.alter_column("organizations", "display_name", existing_type=sa.String(), nullable=False)

    # Populate updated_at for existing rows
    op.execute("UPDATE organizations SET updated_at = created_at WHERE updated_at IS NULL")

    # Now make updated_at NOT NULL with server default
    op.alter_column(
        "organizations",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organizations",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_column("organizations", "deleted_at")
    op.drop_column("organizations", "description")
    op.drop_column("organizations", "display_name")
    # ### end Alembic commands ###
