"""add composite indexes for interview queries

Revision ID: cf2cb0df0936
Revises: bbb78d9096e9
Create Date: 2025-10-11 08:53:23.968681

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cf2cb0df0936"
down_revision: str | Sequence[str] | None = "bbb78d9096e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_interviews_study_external_pid",
        "interviews",
        ["study_id", "external_participant_id"],
        unique=False,
    )
    op.create_index(
        "ix_interviews_study_status_completed",
        "interviews",
        ["study_id", "status", "completed_at"],
        unique=False,
    )
    op.alter_column(
        "participant_profiles",
        "platform_identities",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "participant_profiles",
        "platform_identities",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_index("ix_interviews_study_status_completed", table_name="interviews")
    op.drop_index("ix_interviews_study_external_pid", table_name="interviews")
    # ### end Alembic commands ###
