name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      stack:
        description: 'Pulumi stack to deploy'
        required: true
        type: choice
        options:
          - dev
          - prod
      action:
        description: 'Pulumi action'
        required: true
        type: choice
        default: 'preview'
        options:
          - preview
          - up

jobs:
  deploy-infrastructure:
    name: Deploy to ${{ inputs.stack }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for Workload Identity Federation

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Pulumi CLI
        uses: pulumi/actions@v5

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/331807676337/locations/global/workloadIdentityPools/github/providers/github'
          service_account: 'pulumi-deployer@verity-platform-473406.iam.gserviceaccount.com'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Select Pulumi stack
        working-directory: infra
        run: |
          pulumi stack select ${{ inputs.stack }} --create
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Pulumi Preview
        if: inputs.action == 'preview'
        working-directory: infra
        run: |
          pulumi preview --diff
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Pulumi Up
        if: inputs.action == 'up'
        working-directory: infra
        run: |
          pulumi up --yes --skip-preview
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Export stack outputs
        if: inputs.action == 'up'
        working-directory: infra
        run: |
          echo "## Stack Outputs" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          pulumi stack output --json | jq . >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Deployment summary
        if: inputs.action == 'up'
        run: |
          echo "### ✅ Infrastructure deployed to \`${{ inputs.stack }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Stack:** ${{ inputs.stack }}" >> $GITHUB_STEP_SUMMARY
          echo "**Pulumi Console:** https://app.pulumi.com/$(pulumi whoami)/verity-infra/${{ inputs.stack }}" >> $GITHUB_STEP_SUMMARY
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}